---
- name: Instalar Docker no Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Atualizar pacotes do sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar dependências necessárias
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Adicionar chave GPG oficial do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Adicionar usuário ao grupo Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Iniciar e habilitar serviço Docker
      systemd:
        name: docker
        enabled: yes
        state: started
