name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Instalar o Bicep
        run: |
          az bicep install

      - name: Criar Grupo de Recursos
        run: |
          az group create --name bicep-rg --location eastus

      - name: Implantar Bicep
        run: |
          az deployment group create \
            --resource-group bicep-rg \
            --template-file main.bicep \
            --parameters adminPassword=${{ secrets.ADMIN_PASSWORD }}
