name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: '🔐 Azure Login'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Instalar extensões do Bicep
        run: az bicep install

      - name: Validar template Bicep
        run: az bicep build --file main.bicep

      - name: Executar deploy Bicep
        run: |
          az deployment group create \
            --resource-group mdc-rg \
            --template-file main.bicep
